In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)

### read data

In [3]:
dat = pd.read_csv("test.csv")
dat.head()

          id        date  store_nbr  item_nbr  onpromotion
0  125497040  2017-08-16          1     96995        False
1  125497041  2017-08-16          1     99197        False
2  125497042  2017-08-16          1    103501        False
3  125497043  2017-08-16          1    103520        False
4  125497044  2017-08-16          1    103665        False

In [3]:
dat.shape

(3370464, 5)

### onpromotion

In [5]:
dat.groupby('onpromotion').count()

                  id     date  store_nbr  item_nbr
onpromotion
False        3171867  3171867    3171867   3171867
True          198597   198597     198597    198597

In [6]:
dat['onpromotion'].isnull().sum()

0

In [7]:
3171867+198597

3370464

#### Conclusions:
1. There is null value of onpromotion of test dataset

### item_nbr

In [9]:
dat.groupby('item_nbr').count()

           id  date  store_nbr  onpromotion
item_nbr
96995     864   864        864          864
99197     864   864        864          864
103501    864   864        864          864
103520    864   864        864          864
103665    864   864        864          864
105574    864   864        864          864
105575    864   864        864          864
105576    864   864        864          864
105577    864   864        864          864
105693    864   864        864          864
105737    864   864        864          864
105857    864   864        864          864
106716    864   864        864          864
108079    864   864        864          864
108634    864   864        864          864
108696    864   864        864          864
108698    864   864        864          864
108701    864   864        864          864
108786    864   864        864          864
108797    864   864        864          864
108831    864   864        864          864
108833    864   864        864          864
108862    864   864        864          864
108952    864   864        864          864
111223    864   864        864          864
111397    864   864        864          864
112830    864   864        864          864
114778    864   864        864          864
114790    864   864        864          864
114799    864   864        864          864
...       ...   ...        ...          ...
2127921   864   864        864          864
2127992   864   864        864          864
2128628   864   864        864          864
2128799   864   864        864          864
2129334   864   864        864          864
2129350   864   864        864          864
2129387   864   864        864          864
2129515   864   864        864          864
2129616   864   864        864          864
2129678   864   864        864          864
2129786   864   864        864          864
2129790   864   864        864          864
2129892   864   864        864          864
2129994   864   864        864          864
2130131   864   864        864          864
2130219   864   864        864          864
2130265   864   864        864          864
2130352   864   864        864          864
2130474   864   864        864          864
2130521   864   864        864          864
2130526   864   864        864          864
2130553   864   864        864          864
2131010   864   864        864          864
2131572   864   864        864          864
2131699   864   864        864          864
2132163   864   864        864          864
2132318   864   864        864          864
2132945   864   864        864          864
2132957   864   864        864          864
2134244   864   864        864          864

[3901 rows x 4 columns]

In [14]:
3901*864

3370464

In [19]:
16*54

864

In [20]:
item_2127114 = dat[dat.item_nbr == 2127114]
item_2127114

                id        date  store_nbr  item_nbr  onpromotion
3864     125500904  2017-08-16          1   2127114        False
7765     125504805  2017-08-16          2   2127114        False
11666    125508706  2017-08-16          3   2127114        False
15567    125512607  2017-08-16          4   2127114        False
19468    125516508  2017-08-16          5   2127114        False
23369    125520409  2017-08-16          6   2127114        False
27270    125524310  2017-08-16          7   2127114        False
31171    125528211  2017-08-16          8   2127114        False
35072    125532112  2017-08-16          9   2127114        False
38973    125536013  2017-08-16         10   2127114        False
42874    125539914  2017-08-16         11   2127114        False
46775    125543815  2017-08-16         12   2127114        False
50676    125547716  2017-08-16         13   2127114        False
54577    125551617  2017-08-16         14   2127114        False
58478    125555518  2017-08-16         15   2127114        False
62379    125559419  2017-08-16         16   2127114        False
66280    125563320  2017-08-16         17   2127114        False
70181    125567221  2017-08-16         18   2127114        False
74082    125571122  2017-08-16         19   2127114        False
77983    125575023  2017-08-16         20   2127114        False
81884    125578924  2017-08-16         21   2127114        False
85785    125582825  2017-08-16         22   2127114        False
89686    125586726  2017-08-16         23   2127114        False
93587    125590627  2017-08-16         24   2127114        False
97488    125594528  2017-08-16         25   2127114        False
101389   125598429  2017-08-16         26   2127114        False
105290   125602330  2017-08-16         27   2127114        False
109191   125606231  2017-08-16         28   2127114        False
113092   125610132  2017-08-16         29   2127114        False
116993   125614033  2017-08-16         30   2127114        False
...            ...         ...        ...       ...          ...
3257298  128754338  2017-08-31         25   2127114        False
3261199  128758239  2017-08-31         26   2127114        False
3265100  128762140  2017-08-31         27   2127114        False
3269001  128766041  2017-08-31         28   2127114        False
3272902  128769942  2017-08-31         29   2127114        False
3276803  128773843  2017-08-31         30   2127114        False
3280704  128777744  2017-08-31         31   2127114        False
3284605  128781645  2017-08-31         32   2127114        False
3288506  128785546  2017-08-31         33   2127114        False
3292407  128789447  2017-08-31         34   2127114        False
3296308  128793348  2017-08-31         35   2127114        False
3300209  128797249  2017-08-31         36   2127114        False
3304110  128801150  2017-08-31         37   2127114        False
3308011  128805051  2017-08-31         38   2127114        False
3311912  128808952  2017-08-31         39   2127114        False
3315813  128812853  2017-08-31         40   2127114        False
3319714  128816754  2017-08-31         41   2127114        False
3323615  128820655  2017-08-31         42   2127114        False
3327516  128824556  2017-08-31         43   2127114        False
3331417  128828457  2017-08-31         44   2127114        False
3335318  128832358  2017-08-31         45   2127114        False
3339219  128836259  2017-08-31         46   2127114        False
3343120  128840160  2017-08-31         47   2127114        False
3347021  128844061  2017-08-31         48   2127114        False
3350922  128847962  2017-08-31         49   2127114        False
3354823  128851863  2017-08-31         50   2127114        False
3358724  128855764  2017-08-31         51   2127114        False
3362625  128859665  2017-08-31         52   2127114        False
3366526  128863566  2017-08-31         53   2127114        False
3370427  128867467  2017-08-31         54   2127114        False

[864 rows x 5 columns]

#### Conclusions:
1. There are 3901 items
2. Every iterms has 864 records, which are the permutation of combination of stores and dates

### date

In [12]:
dat.groupby('date').count()

                id  store_nbr  item_nbr  onpromotion
date
2017-08-16  210654     210654    210654       210654
2017-08-17  210654     210654    210654       210654
2017-08-18  210654     210654    210654       210654
2017-08-19  210654     210654    210654       210654
2017-08-20  210654     210654    210654       210654
2017-08-21  210654     210654    210654       210654
2017-08-22  210654     210654    210654       210654
2017-08-23  210654     210654    210654       210654
2017-08-24  210654     210654    210654       210654
2017-08-25  210654     210654    210654       210654
2017-08-26  210654     210654    210654       210654
2017-08-27  210654     210654    210654       210654
2017-08-28  210654     210654    210654       210654
2017-08-29  210654     210654    210654       210654
2017-08-30  210654     210654    210654       210654
2017-08-31  210654     210654    210654       210654

In [13]:
210654*16

3370464

#### Conclusions:
1. The date span starts from 2017/8/16 to 2017/8/31
2. Every date has 210654 records.

### store_nbr

In [16]:
dat.groupby('store_nbr').count()

              id   date  item_nbr  onpromotion
store_nbr
1          62416  62416     62416        62416
2          62416  62416     62416        62416
3          62416  62416     62416        62416
4          62416  62416     62416        62416
5          62416  62416     62416        62416
6          62416  62416     62416        62416
7          62416  62416     62416        62416
8          62416  62416     62416        62416
9          62416  62416     62416        62416
10         62416  62416     62416        62416
11         62416  62416     62416        62416
12         62416  62416     62416        62416
13         62416  62416     62416        62416
14         62416  62416     62416        62416
15         62416  62416     62416        62416
16         62416  62416     62416        62416
17         62416  62416     62416        62416
18         62416  62416     62416        62416
19         62416  62416     62416        62416
20         62416  62416     62416        62416
21         62416  62416     62416        62416
22         62416  62416     62416        62416
23         62416  62416     62416        62416
24         62416  62416     62416        62416
25         62416  62416     62416        62416
26         62416  62416     62416        62416
27         62416  62416     62416        62416
28         62416  62416     62416        62416
29         62416  62416     62416        62416
30         62416  62416     62416        62416
31         62416  62416     62416        62416
32         62416  62416     62416        62416
33         62416  62416     62416        62416
34         62416  62416     62416        62416
35         62416  62416     62416        62416
36         62416  62416     62416        62416
37         62416  62416     62416        62416
38         62416  62416     62416        62416
39         62416  62416     62416        62416
40         62416  62416     62416        62416
41         62416  62416     62416        62416
42         62416  62416     62416        62416
43         62416  62416     62416        62416
44         62416  62416     62416        62416
45         62416  62416     62416        62416
46         62416  62416     62416        62416
47         62416  62416     62416        62416
48         62416  62416     62416        62416
49         62416  62416     62416        62416
50         62416  62416     62416        62416
51         62416  62416     62416        62416
52         62416  62416     62416        62416
53         62416  62416     62416        62416
54         62416  62416     62416        62416

In [17]:
62416*54

3370464

#### Conclusions:
1. There are 54 stores
2. Every store has 62416 records

### Find items that test data has but are not contained in the training data

In [4]:
data = pd.read_csv("train.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [33]:
data_item = data[['item_nbr']]

In [34]:
dat_item = dat[['item_nbr']]

In [35]:
data_item = data_item.drop_duplicates()

In [36]:
data_item.shape

(4036, 1)

In [37]:
dat_item = dat_item.drop_duplicates()

In [38]:
dat_item.shape

(3901, 1)

In [14]:
common = data_item.merge(dat_item, on = "item_nbr")

In [46]:
common = common['item_nbr'].tolist()

In [39]:
data_item = data_item['item_nbr'].tolist()

In [41]:
data_item

[103665,
 105574,
 105575,
 108079,
 108701,
 108786,
 108797,
 108952,
 111397,
 114790,
 114800,
 115267,
 115611,
 115693,
 115720,
 115850,
 115891,
 115892,
 115894,
 119024,
 119026,
 119141,
 119187,
 119624,
 123927,
 129635,
 153239,
 153267,
 153395,
 155607,
 158680,
 158788,
 158842,
 158875,
 158956,
 159156,
 162066,
 164036,
 164088,
 165550,
 165551,
 165553,
 165594,
 165704,
 165705,
 165718,
 165988,
 168927,
 169104,
 172184,
 172343,
 173113,
 177050,
 179600,
 205387,
 207857,
 208384,
 208498,
 208514,
 211203,
 214381,
 214862,
 215331,
 215332,
 215352,
 215356,
 215370,
 219147,
 219150,
 220435,
 222879,
 223434,
 224081,
 226857,
 227111,
 246052,
 252970,
 252972,
 253103,
 257847,
 257848,
 258268,
 258396,
 260893,
 261052,
 261053,
 261700,
 262358,
 265254,
 265257,
 265258,
 265266,
 265559,
 268440,
 268443,
 268664,
 268676,
 268834,
 273528,
 275823,
 275826,
 279494,
 302997,
 305080,
 305081,
 305227,
 305229,
 305344,
 308085,
 308726,
 308916,
 310644,
 311954,
 311994,
 312324,
 313641,
 314384,
 314393,
 314570,
 315176,
 315179,
 315220,
 315277,
 315320,
 315322,
 315460,
 315463,
 315474,
 318787,
 318847,
 319093,
 319094,
 320682,
 323013,
 323227,
 323921,
 324206,
 329362,
 329397,
 346066,
 352513,
 355090,
 358096,
 358100,
 358231,
 358515,
 360314,
 361502,
 362035,
 363868,
 364413,
 364606,
 364738,
 364829,
 364834,
 365138,
 368140,
 368424,
 368624,
 368628,
 369432,
 370042,
 371437,
 372480,
 373152,
 374464,
 376427,
 378685,
 402174,
 406965,
 407769,
 410257,
 410866,
 414305,
 414353,
 414426,
 414478,
 414621,
 414623,
 414750,
 414752,
 414888,
 417765,
 417835,
 418235,
 420720,
 422452,
 426155,
 428488,
 452212,
 456870,
 456875,
 457424,
 457425,
 457574,
 457688,
 457928,
 458029,
 459762,
 462673,
 463598,
 464263,
 464333,
 464336,
 464339,
 464374,
 464385,
 464536,
 464906,
 468058,
 470625,
 471985,
 472526,
 502182,
 502227,
 502331,
 507457,
 507478,
 507479,
 507867,
 507927,
 509877,
 510054,
 510055,
 514172,
 514242,
 514327,
 517903,
 518091,
 518094,
 519560,
 521818,
 522721,
 552050,
 554047,
 554049,
 556698,
 557256,
 557257,
 557285,
 557408,
 557420,
 558730,
 559044,
 559870,
 559873,
 563966,
 564272,
 564274,
 564533,
 567623,
 567778,
 567781,
 567787,
 568133,
 575863,
 575875,
 577745,
 578097,
 580929,
 581078,
 582863,
 582864,
 583795,
 583797,
 583799,
 583868,
 583925,
 583927,
 583931,
 583968,
 583973,
 584026,
 584028,
 584076,
 584078,
 584188,
 586969,
 587069,
 587156,
 587186,
 594045,
 617092,
 617548,
 621300,
 623316,
 627263,
 633997,
 634009,
 634010,
 634014,
 634054,
 636846,
 637016,
 638240,
 638308,
 638327,
 641042,
 651523,
 655840,
 657869,
 660502,
 660503,
 664539,
 668754,
 671039,
 671051,
 671062,
 671076,
 671079,
 671083,
 671684,
 671699,
 671706,
 671708,
 679442,
 679602,
 683722,
 683723,
 692104,
 692531,
 692537,
 699692,
 699693,
 699703,
 700609,
 716250,
 723184,
 723210,
 724003,
 730258,
 730259,
 732006,
 732007,
 740713,
 740714,
 742735,
 742738,
 743494,
 743496,
 743497,
 749421,
 749720,
 752987,
 757880,
 758861,
 759651,
 759697,
 759698,
 759893,
 762405,
 765092,
 765518,
 767183,
 769312,
 769314,
 771156,
 779122,
 781794,
 781796,
 781797,
 781798,
 783243,
 789223,
 789224,
 789905,
 795612,
 796396,
 801217,
 802832,
 802833,
 804932,
 805788,
 807493,
 809183,
 812716,
 812751,
 812769,
 816606,
 819194,
 819195,
 819206,
 819209,
 819231,
 823245,
 827911,
 828204,
 828632,
 829389,
 830624,
 830625,
 830797,
 838215,
 838216,
 838217,
 838406,
 838407,
 838408,
 839362,
 839363,
 839544,
 839545,
 841197,
 841612,
 841841,
 843462,
 843585,
 844017,
 844019,
 847859,
 847863,
 847894,
 848765,
 848953,
 849098,
 850333,
 850460,
 851982,
 852620,
 856687,
 859529,
 859932,
 860548,
 862213,
 862454,
 864510,
 868529,
 870545,
 870546,
 871421,
 872317,
 874990,
 875604,
 878715,
 882624,
 885543,
 888689,
 890213,
 890215,
 890371,
 890372,
 895291,
 902839,
 906979,
 907684,
 908741,
 911429,
 911871,
 913363,
 913364,
 913521,
 913964,
 913966,
 915310,
 915822,
 915980,
 916885,
 916886,
 926958,
 930247,
 936994,
 938125,
 938126,
 938129,
 938566,
 938567,
 938575,
 938576,
 938657,
 938659,
 939207,
 939662,
 940591,
 940616,
 949297,
 949299,
 949511,
 953427,
 953428,
 953562,
 953609,
 954553,
 956012,
 956014,
 957098,
 958016,
 958514,
 968432,
 968935,
 968936,
 968937,
 979197,
 979199,
 988459,
 991329,
 996122,
 996600,
 999545,
 1003679,
 1004550,
 1004551,
 1009998,
 1014865,
 1020237,
 1028589,
 1037838,
 1037845,
 1037856,
 1037857,
 1038952,
 1040170,
 1044592,
 1047675,
 1047679,
 1047680,
 1047681,
 1047685,
 1047686,
 1047690,
 1047696,
 1047698,
 1047702,
 1047703,
 1047705,
 1047717,
 1047733,
 1047743,
 1047755,
 1047756,
 1047757,
 1047758,
 1047772,
 1047773,
 1047774,
 1047775,
 1047786,
 1047790,
 1052022,
 1052563,
 1060036,
 1062374,
 1066900,
 1066901,
 1070962,
 1071949,
 1074327,
 1076066,
 1076155,
 1079214,
 1079329,
 1080021,
 1080756,
 1081359,
 1083152,
 1083196,
 1084881,
 1084882,
 1085246,
 1086172,
 1087270,
 1088002,
 1089046,
 1089843,
 1089844,
 1090401,
 1091365,
 1091366,
 1097187,
 1101724,
 1102268,
 1102971,
 1102975,
 1102976,
 1104599,
 1105212,
 1105214,
 1109325,
 1109389,
 105577,
 105737,
 105857,
 106716,
 108696,
 108698,
 108831,
 108862,
 111223,
 112830,
 114778,
 114799,
 115893,
 116017,
 116018,
 116279,
 116311,
 119023,
 119191,
 121964,
 122095,
 122419,
 122425,
 123347,
 123601,
 125430,
 127534,
 127547,
 129296,
 129297,
 129758,
 153078,
 153398,
 155601,
 155610,
 155621,
 155625,
 158789,
 159242,
 164037,
 164647,
 165727,
 167437,
 168930,
 168989,
 169101,
 170791,
 173111,
 174081,
 177395,
 179274,
 179564,
 179615,
 205486,
 205557,
 208386,
 208426,
 208539,
 208659,
 208699,
 209085,
 210520,
 210798,
 211205,
 211999,
 212550,
 213066,
 213652,
 213653,
 213788,
 214860,
 215303,
 215327,
 215468,
 215896,
 218726,
 220613,
 221506,
 222975,
 223136,
 226126,
 227728,
 229368,
 252698,
 253145,
 255161,
 255202,
 258376,
 258395,
 258411,
 260669,
 262991,
 264299,
 264300,
 264452,
 264576,
 264751,
 264752,
 264753,
 265237,
 265279,
 265382,
 265672,
 265700,
 268623,
 268662,
 269029,
 269084,
 270522,
 271478,
 271479,
 273859,
 279157,
 302952,
 302998,
 305079,
 305341,
 308766,
 308924,
 310647,
 310671,
 312113,
 312596,
 314881,
 315178,
 315180,
 315221,
 315279,
 315712,
 315713,
 317285,
 318932,
 318935,
 319095,
 322095,
 329070,
 329071,
 346065,
 354922,
 355091,
 357996,
 358232,
 358264,
 358272,
 358519,
 358561,
 359913,
 360313,
 360703,
 360704,
 362548,
 363049,
 363889,
 363895,
 364724,
 364832,
 364865,
 365139,
 365140,
 365264,
 368136,
 368213,
 368260,
 368419,
 371130,
 371218,
 371438,
 372924,
 378332,
 401817,
 401911,
 402136,
 402175,
 404336,
 405304,
 407499,
 407608,
 409738,
 409739,
 409904,
 411487,
 411555,
 413986,
 413987,
 414354,
 414421,
 414454,
 414620,
 418025,
 418026,
 421066,
 428054,
 428394,
 452022,
 454326,
 454426,
 454589,
 454596,
 457556,
 460804,
 463458,
 463816,
 463901,
 463903,
 464302,
 464356,
 464940,
 467808,
 468057,
 469643,
 470624,
 470762,
 471980,
 472658,
 476261,
 502224,
 502230,
 506717,
 507354,
 507641,
 507870,
 507969,
 508069,
 508947,
 510057,
 513379,
 513853,
 513855,
 514144,
 514149,
 514446,
 514597,
 514757,
 517615,
 517904,
 517905,
 517906,
 517909,
 522383,
 522941,
 523054,
 525887,
 525902,
 527757,
 554048,
 554143,
 557286,
 557305,
 557810,
 559494,
 559680,
 559682,
 559872,
 563654,
 564110,
 564287,
 564288,
 564534,
 567579,
 567588,
 567779,
 570869,
 570917,
 570922,
 572838,
 574898,
 575630,
 575876,
 577740,
 577741,
 577743,
 578467,
 581742,
 582865,
 584027,
 584099,
 586823,
 586911,
 589403,
 592801,
 592942,
 598414,
 598492,
 617096,
 617763,
 619969,
 627887,
 633996,
 634008,
 634015,
 638296,
 639586,
 645294,
 648313,
 651326,
 655427,
 655749,
 658608,
 664537,
 664543,
 664545,
 668752,
 668753,
 671084,
 679926,
 681606,
 682321,
 683721,
 686036,
 691945,
 692105,
 692106,
 695758,
 699686,
 699688,
 716241,
 716242,
 716245,
 724359,
 724360,
 724403,
 724498,
 729337,
 736128,
 740722,
 740723,
 741201,
 750856,
 750857,
 757888,
 759694,
 759894,
 764438,
 764439,
 765517,
 765520,
 770453,
 770463,
 771157,
 776057,
 793341,
 793346,
 794245,
 795610,
 795611,
 796394,
 796395,
 799461,
 801934,
 802831,
 804503,
 809882,
 812725,
 812726,
 812757,
 813167,
 813769,
 816679,
 818590,
 819228,
 819230,
 819932,
 819934,
 820645,
 821186,
 828630,
 830806,
 833396,
 833644,
 838409,
 838412,
 838413,
 838415,
 838875,
 839367,
 841514,
 841570,
 841607,
 841614,
 841667,
 841842,
 843411,
 843610,
 846163,
 846565,
 849095,
 849139,
 849142,
 849312,
 850542,
 852110,
 852937,
 852938,
 853195,
 853196,
 859966,
 864290,
 864508,
 864511,
 865147,
 865155,
 866927,
 870544,
 870938,
 871118,
 872308,
 876223,
 876663,
 877513,
 877514,
 881701,
 881910,
 881911,
 881912,
 884878,
 885553,
 886067,
 886396,
 886398,
 888682,
 888761,
 888763,
 ...]

In [42]:
dat_item = dat_item['item_nbr'].tolist()

In [43]:
dat_item

[96995,
 99197,
 103501,
 103520,
 103665,
 105574,
 105575,
 105576,
 105577,
 105693,
 105737,
 105857,
 106716,
 108079,
 108634,
 108696,
 108698,
 108701,
 108786,
 108797,
 108831,
 108833,
 108862,
 108952,
 111223,
 111397,
 112830,
 114778,
 114790,
 114799,
 114800,
 115267,
 115611,
 115693,
 115720,
 115847,
 115850,
 115891,
 115892,
 115893,
 115894,
 116017,
 116018,
 116279,
 116311,
 119023,
 119024,
 119026,
 119141,
 119187,
 119191,
 119193,
 119624,
 121964,
 122095,
 122419,
 122425,
 123347,
 123601,
 123602,
 123927,
 125430,
 127534,
 127547,
 129296,
 129297,
 129635,
 129758,
 129759,
 153078,
 153239,
 153267,
 153395,
 153398,
 155499,
 155500,
 155600,
 155601,
 155607,
 155610,
 155621,
 155625,
 157956,
 158680,
 158788,
 158789,
 158842,
 158875,
 158956,
 159156,
 159242,
 161288,
 162066,
 164036,
 164037,
 164088,
 164647,
 165550,
 165551,
 165553,
 165594,
 165693,
 165704,
 165705,
 165718,
 165727,
 165988,
 167437,
 168927,
 168930,
 168931,
 168989,
 169028,
 169101,
 169104,
 170791,
 171890,
 172184,
 172343,
 172995,
 173111,
 173113,
 174081,
 176411,
 177050,
 177395,
 179274,
 179564,
 179579,
 179615,
 205209,
 205381,
 205387,
 205486,
 205557,
 207857,
 208384,
 208386,
 208426,
 208498,
 208514,
 208530,
 208539,
 208659,
 208699,
 209085,
 210520,
 210798,
 211203,
 211205,
 211206,
 211999,
 212550,
 212552,
 213066,
 213652,
 213653,
 213788,
 214381,
 214859,
 214860,
 214862,
 215303,
 215304,
 215327,
 215331,
 215332,
 215352,
 215356,
 215370,
 215468,
 215896,
 217827,
 218726,
 218728,
 219147,
 219150,
 219152,
 220432,
 220435,
 220613,
 221506,
 222879,
 222975,
 223068,
 223136,
 223434,
 223463,
 224081,
 226126,
 226857,
 227111,
 227728,
 229368,
 246052,
 250782,
 252698,
 252970,
 252972,
 253103,
 253145,
 255161,
 255198,
 255199,
 255202,
 257847,
 257848,
 258268,
 258376,
 258395,
 258396,
 258411,
 258537,
 260628,
 260669,
 260893,
 261052,
 261053,
 261700,
 262358,
 262991,
 263583,
 264299,
 264300,
 264305,
 264452,
 264576,
 264751,
 264752,
 264753,
 265237,
 265254,
 265257,
 265258,
 265279,
 265382,
 265559,
 265672,
 265700,
 268440,
 268443,
 268446,
 268623,
 268662,
 268664,
 268676,
 268834,
 269036,
 269084,
 269286,
 269287,
 270522,
 271478,
 271479,
 273528,
 273859,
 275823,
 275826,
 276560,
 278806,
 279125,
 279137,
 279157,
 279494,
 302824,
 302952,
 302995,
 302997,
 302998,
 305074,
 305079,
 305080,
 305081,
 305227,
 305229,
 305234,
 305237,
 305341,
 305344,
 305345,
 307740,
 308085,
 308726,
 308766,
 308916,
 308924,
 310644,
 310647,
 310671,
 310790,
 311954,
 311994,
 312113,
 312317,
 312324,
 312596,
 313094,
 313641,
 314384,
 314393,
 314570,
 314879,
 314880,
 314881,
 315176,
 315178,
 315179,
 315220,
 315221,
 315277,
 315279,
 315320,
 315322,
 315460,
 315463,
 315473,
 315474,
 315712,
 315713,
 317147,
 317285,
 318787,
 318847,
 318932,
 318935,
 319093,
 319094,
 319095,
 319272,
 320681,
 320682,
 321798,
 322094,
 322095,
 323013,
 323217,
 323227,
 323921,
 324206,
 326951,
 329070,
 329071,
 329361,
 329362,
 329364,
 329365,
 329397,
 346065,
 346066,
 346406,
 352513,
 354918,
 354919,
 354922,
 354971,
 355090,
 355091,
 357961,
 357962,
 357963,
 357996,
 358096,
 358100,
 358134,
 358231,
 358232,
 358264,
 358272,
 358515,
 358519,
 358561,
 358564,
 359913,
 360313,
 360314,
 360703,
 360704,
 360705,
 361502,
 362035,
 362548,
 363049,
 363868,
 363889,
 363895,
 364413,
 364606,
 364724,
 364738,
 364829,
 364832,
 364834,
 364865,
 365138,
 365139,
 365140,
 365264,
 368136,
 368139,
 368140,
 368213,
 368260,
 368270,
 368419,
 368424,
 368624,
 369432,
 370042,
 371130,
 371218,
 371434,
 371437,
 371438,
 372369,
 372480,
 372924,
 372937,
 373152,
 374464,
 376194,
 376427,
 377978,
 378330,
 378332,
 378685,
 401817,
 401911,
 402136,
 402174,
 402175,
 402299,
 404332,
 404333,
 404334,
 404336,
 404439,
 404442,
 404454,
 405304,
 406965,
 407499,
 407500,
 407533,
 407542,
 407552,
 407608,
 407769,
 409738,
 409739,
 409904,
 410150,
 410257,
 411487,
 411555,
 411557,
 413557,
 413986,
 413987,
 414353,
 414354,
 414421,
 414425,
 414426,
 414454,
 414455,
 414478,
 414620,
 414621,
 414623,
 414750,
 414752,
 414888,
 417763,
 417765,
 417835,
 418024,
 418025,
 418026,
 418235,
 418238,
 419729,
 420720,
 421066,
 422452,
 428054,
 428394,
 428488,
 437609,
 452022,
 452078,
 452079,
 452212,
 454326,
 454413,
 454414,
 454416,
 454426,
 454589,
 454593,
 454596,
 456870,
 456875,
 457424,
 457425,
 457471,
 457556,
 457574,
 457688,
 457727,
 457928,
 458029,
 459762,
 459801,
 459804,
 460804,
 461432,
 461752,
 462673,
 463458,
 463598,
 463816,
 463901,
 463903,
 464112,
 464263,
 464302,
 464333,
 464334,
 464336,
 464339,
 464356,
 464374,
 464385,
 464536,
 464906,
 464907,
 464940,
 467808,
 467887,
 468057,
 468058,
 468265,
 469643,
 470624,
 470625,
 470760,
 470762,
 471980,
 471985,
 472314,
 472526,
 472645,
 472658,
 476261,
 476707,
 479200,
 502067,
 502182,
 502224,
 502227,
 502230,
 502331,
 504457,
 506717,
 507354,
 507457,
 507478,
 507479,
 507641,
 507867,
 507870,
 507927,
 507958,
 507969,
 508069,
 508947,
 509872,
 509877,
 510052,
 510054,
 510055,
 510057,
 511172,
 511394,
 511397,
 513379,
 513853,
 513855,
 514144,
 514149,
 514172,
 514242,
 514444,
 514445,
 514446,
 514597,
 514729,
 514730,
 514757,
 517615,
 517903,
 517904,
 517905,
 517906,
 517909,
 518091,
 518094,
 519560,
 519718,
 521818,
 522383,
 522721,
 522941,
 523054,
 525887,
 525902,
 527757,
 546043,
 551893,
 552050,
 554047,
 554048,
 554049,
 554143,
 554144,
 554145,
 554152,
 556698,
 557241,
 557256,
 557257,
 557285,
 557286,
 557289,
 557305,
 557408,
 557810,
 558730,
 559044,
 559493,
 559494,
 559680,
 559682,
 559870,
 559872,
 559873,
 562568,
 563654,
 563966,
 564110,
 564272,
 564274,
 564287,
 564288,
 564533,
 564534,
 567517,
 567579,
 567588,
 567623,
 567750,
 567778,
 567779,
 567781,
 567787,
 568133,
 570869,
 570870,
 570917,
 570922,
 572838,
 573832,
 574898,
 575630,
 575675,
 575863,
 575875,
 575876,
 577740,
 577741,
 577743,
 577745,
 578097,
 578467,
 579759,
 580929,
 581078,
 581742,
 582863,
 582864,
 582865,
 583795,
 583797,
 583799,
 583868,
 583925,
 583927,
 583931,
 583968,
 583973,
 583975,
 583977,
 583978,
 583985,
 584026,
 584027,
 584028,
 584030,
 584032,
 584076,
 584077,
 584078,
 584099,
 584101,
 584103,
 584123,
 584125,
 584126,
 584129,
 584188,
 584246,
 586423,
 586823,
 586824,
 586911,
 586967,
 586969,
 587069,
 587104,
 587156,
 587157,
 587186,
 589403,
 592801,
 592942,
 594045,
 598414,
 598492,
 608035,
 617092,
 617096,
 617103,
 617113,
 617548,
 619965,
 619969,
 621300,
 622958,
 623316,
 623317,
 623330,
 627263,
 627885,
 627887,
 633735,
 633977,
 633996,
 633997,
 634008,
 634009,
 634010,
 634014,
 634015,
 634054,
 636846,
 637016,
 638240,
 638296,
 638308,
 638327,
 638977,
 638978,
 640286,
 641042,
 641627,
 645294,
 648313,
 651326,
 651523,
 651525,
 655427,
 655744,
 655749,
 655840,
 657869,
 658608,
 658609,
 660310,
 660311,
 660312,
 660318,
 660319,
 660320,
 660321,
 660323,
 660502,
 660503,
 661582,
 663084,
 664537,
 664539,
 664543,
 664545,
 668752,
 668753,
 668754,
 671039,
 671051,
 671055,
 671062,
 671066,
 671067,
 671068,
 671076,
 671079,
 671083,
 671084,
 671684,
 671699,
 671706,
 671708,
 671908,
 673306,
 673415,
 679442,
 679602,
 679603,
 679926,
 681606,
 682321,
 682884,
 683720,
 683721,
 683722,
 683723,
 686034,
 686035,
 686036,
 687549,
 688279,
 691945,
 692104,
 692105,
 692106,
 692531,
 692537,
 695758,
 696183,
 698642,
 698643,
 699686,
 699687,
 699688,
 699689,
 699692,
 699693,
 699703,
 699745,
 700607,
 700609,
 700610,
 716241,
 716242,
 716245,
 716250,
 723184,
 723210,
 724003,
 724360,
 724403,
 724498,
 729337,
 730258,
 732006,
 732007,
 736128,
 738219,
 740713,
 740714,
 740722,
 740723,
 740726,
 740728,
 740729,
 741201,
 741922,
 742735,
 742738,
 743494,
 743496,
 743497,
 749421,
 749720,
 749729,
 750855,
 750856,
 750857,
 751759,
 752167,
 752987,
 754103,
 757880,
 757888,
 757889,
 758861,
 759651,
 759657,
 759694,
 759697,
 759698,
 759890,
 759893,
 759894,
 760319,
 762405,
 764438,
 764439,
 765092,
 765517,
 765518,
 765519,
 765520,
 767183,
 767184,
 769312,
 769314,
 770453,
 770456,
 770461,
 770463,
 770511,
 771156,
 771157,
 776057,
 776622,
 779122,
 781794,
 781796,
 781797,
 781798,
 781936,
 783243,
 787426,
 788172,
 788708,
 789223,
 789224,
 789904,
 789905,
 789906,
 789907,
 793341,
 793345,
 793346,
 794245,
 795610,
 795611,
 795612,
 796394,
 796395,
 796396,
 799461,
 800958,
 801217,
 801934,
 802831,
 802832,
 802833,
 803101,
 804098,
 804503,
 804932,
 804974,
 805310,
 805311,
 805321,
 805788,
 807493,
 807495,
 809183,
 809184,
 809882,
 812716,
 812725,
 812726,
 812728,
 812735,
 812751,
 812757,
 812769,
 813167,
 813760,
 816606,
 816679,
 818588,
 818590,
 819194,
 819195,
 819206,
 819209,
 ...]

In [47]:
test_not_train = list(set(dat_item) - set(common))

In [48]:
test_not_train

[313094,
 2129678,
 2109969,
 2117783,
 2120216,
 2112280,
 2015646,
 1464607,
 2128799,
 2124705,
 2127651,
 2130474,
 2130219,
 2112303,
 2130352,
 2127024,
 2127921,
 2129334,
 2127544,
 2120506,
 2120768,
 2131010,
 2132163,
 2129350,
 2127175,
 2129994,
 2112461,
 2112462,
 1467088,
 2132945,
 2127825,
 2130131,
 2129616,
 1467093,
 2130521,
 2130265,
 2132957,
 2132318,
 2130526,
 2127069,
 2112607,
 2129786,
 2134244,
 2129892,
 2127206,
 2121319,
 2126696,
 2120681,
 2129387,
 2129515,
 2131699,
 2131572,
 2127733,
 2125814,
 2120180,
 2127992,
 2130553,
 2128628,
 2118397,
 2129790]

In [52]:
df = pd.DataFrame(test_not_train)

In [55]:
df.columns = ['item_nbr']
df

    item_nbr
0     313094
1    2129678
2    2109969
3    2117783
4    2120216
5    2112280
6    2015646
7    1464607
8    2128799
9    2124705
10   2127651
11   2130474
12   2130219
13   2112303
14   2130352
15   2127024
16   2127921
17   2129334
18   2127544
19   2120506
20   2120768
21   2131010
22   2132163
23   2129350
24   2127175
25   2129994
26   2112461
27   2112462
28   1467088
29   2132945
30   2127825
31   2130131
32   2129616
33   1467093
34   2130521
35   2130265
36   2132957
37   2132318
38   2130526
39   2127069
40   2112607
41   2129786
42   2134244
43   2129892
44   2127206
45   2121319
46   2126696
47   2120681
48   2129387
49   2129515
50   2131699
51   2131572
52   2127733
53   2125814
54   2120180
55   2127992
56   2130553
57   2128628
58   2118397
59   2129790

In [56]:
df.to_csv('item_in_test_but_not_in_train.csv', index = False)

### Find items that train data has but are not contained in the test data

In [49]:
train_not_test = list(set(data_item) - set(common))

In [50]:
train_not_test

[1463810,
 1463814,
 1422347,
 1463823,
 1449487,
 1084436,
 1935388,
 1036317,
 1328672,
 864290,
 1920035,
 1397797,
 1911336,
 1397802,
 1456171,
 1158705,
 958514,
 265266,
 122418,
 1924661,
 1352758,
 1950263,
 1924662,
 1948220,
 1929795,
 1695813,
 1929797,
 1997895,
 1964111,
 1463896,
 1418842,
 871514,
 1463900,
 1229919,
 414305,
 639586,
 874593,
 856687,
 1990768,
 1148017,
 1148018,
 856688,
 1980532,
 603255,
 1974921,
 2048139,
 1360013,
 1359503,
 1988754,
 730259,
 354964,
 1074327,
 1458842,
 2015898,
 1458844,
 1918621,
 716958,
 1243803,
 1047709,
 376483,
 1243817,
 426155,
 1455790,
 1949872,
 679604,
 1210038,
 2011329,
 675524,
 1950405,
 1939144,
 813769,
 1467082,
 813770,
 1166036,
 847575,
 673496,
 1464027,
 819933,
 819934,
 1173213,
 1915102,
 1990881,
 269029,
 1239789,
 1239790,
 1239791,
 1239792,
 2075374,
 410866,
 1239794,
 1418484,
 1239796,
 1239798,
 1239800,
 2048248,
 1239806,
 1998078,
 1320708,
 1239813,
 1239820,
 2002703,
 2004754,
 514327,
 2005274,
 617763,
 885543,
 988459,
 315180,
 1965358,
 1391408,
 1460018,
 1944889,
 1334074,
 1105210,
 1960765,
 1163583,
 2010945,
 1124164,
 1124165,
 1463625,
 1463626,
 1253708,
 1463632,
 846163,
 1980755,
 1463637,
 2005335,
 567644,
 1920863,
 1090401,
 1152355,
 315753,
 557420,
 830829,
 1965425,
 2048374,
 1321336,
 1976186,
 265086,
 1112450,
 1993091,
 1948550,
 724359,
 2014089,
 859529,
 1143691,
 1963404,
 770447,
 179600,
 770449,
 1066900,
 2037148,
 1398687,
 1398688,
 1254310,
 1466286,
 2030002,
 1464246,
 1981370,
 1954748,
 1919933,
 1919935,
 1464256,
 1919937,
 1464257,
 1963459,
 1370564,
 1464258,
 2013632,
 1114567,
 930247,
 1719236,
 959437,
 1466830,
 1898959,
 1466832,
 1898960,
 1898961,
 2034132,
 1471956,
 1976284,
 2017245,
 1949662,
 1238497,
 2010082,
 1097187,
 1919977,
 2049003,
 1459697,
 847859,
 368628,
 2008567,
 1464312,
 416252,
 1914367]

In [57]:
df = pd.DataFrame(train_not_test)
df.columns = ['item_nbr']
df

     item_nbr
0     1463810
1     1463814
2     1422347
3     1463823
4     1449487
5     1084436
6     1935388
7     1036317
8     1328672
9      864290
10    1920035
11    1397797
12    1911336
13    1397802
14    1456171
15    1158705
16     958514
17     265266
18     122418
19    1924661
20    1352758
21    1950263
22    1924662
23    1948220
24    1929795
25    1695813
26    1929797
27    1997895
28    1964111
29    1463896
..        ...
165   1963459
166   1370564
167   1464258
168   2013632
169   1114567
170    930247
171   1719236
172    959437
173   1466830
174   1898959
175   1466832
176   1898960
177   1898961
178   2034132
179   1471956
180   1976284
181   2017245
182   1949662
183   1238497
184   2010082
185   1097187
186   1919977
187   2049003
188   1459697
189    847859
190    368628
191   2008567
192   1464312
193    416252
194   1914367

[195 rows x 1 columns]

In [58]:
df.to_csv('item_in_train_but_not_in_test.csv', index = False)